<?php
/**
 *  Copyright 2014 Taxamo, Ltd.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class By_taxation_type {

  static $swaggerTypes = array(
      'taxed_count' => 'number',
      'deducted_count' => 'number',
      'transactions_count' => 'number'

    );

  /**
  * Number of taxed transactions.
  */
  public $taxed_count; // number
  /**
  * Number of tax deducted transactions.
  */
  public $deducted_count; // number
  /**
  * Total number of transactions
  */
  public $transactions_count; // number
  }

