<?php
/**
 *  Copyright 2014 Taxamo, Ltd.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Countries {

  static $swaggerTypes = array(
      'by_2003_rules' => 'country_schema',
      'detected' => 'country_schema',
      'by_tax_number' => 'country_schema',
      'self_declaration' => 'country_schema',
      'by_cc' => 'country_schema',
      'by_ip' => 'country_schema',
      'by_token' => 'country_schema',
      'by_billing' => 'country_schema',
      'guessed_from_ip' => 'country_schema',
      'other_commercially_relevant_info' => 'country_schema',
      'forced' => 'country_schema'

    );

  /**
  * Used when merchant uses 2003 EU VAT rules.
  */
  public $by_2003_rules; // country_schema
  /**
  * Country detected from other evidence
  */
  public $detected; // country_schema
  /**
  * Country detected from EU TAX number
  */
  public $by_tax_number; // country_schema
  /**
  * Self declared country as evidence.
  */
  public $self_declaration; // country_schema
  /**
  * Country detected by credit card number prefix
  */
  public $by_cc; // country_schema
  /**
  * Country detected by IP
  */
  public $by_ip; // country_schema
  /**
  * Country detected from SMS token
  */
  public $by_token; // country_schema
  /**
  * Country detected by billing country code
  */
  public $by_billing; // country_schema
  /**
  * Country guessed from IP due to lack of other evidence
  */
  public $guessed_from_ip; // country_schema
  /**
  * Additional evidence held by the merchant.
  */
  public $other_commercially_relevant_info; // country_schema
  /**
  * Country forced by paramters
  */
  public $forced; // country_schema
  }

