<?php
/**
 *  Copyright 2014 Taxamo, Ltd.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Invoice_address {

  static $swaggerTypes = array(
      'freeform_address' => 'string',
      'building_number' => 'string',
      'street_name' => 'string',
      'address_detail' => 'string',
      'city' => 'string',
      'postal_code' => 'string',
      'region' => 'string',
      'country' => 'string'

    );

  /**
  * Freeform address. Use when structured data is not available. Will be used in SAF-MOSS file if other fields are not provided.
  */
  public $freeform_address; // string
  /**
  * Building number.
  */
  public $building_number; // string
  /**
  *  Street name.
  */
  public $street_name; // string
  /**
  * Address details - for example apartament number.
  */
  public $address_detail; // string
  /**
  * City name.
  */
  public $city; // string
  /**
  * Postal code.
  */
  public $postal_code; // string
  /**
  * Region.
  */
  public $region; // string
  /**
  * 2-letter ISO country code.
  */
  public $country; // string
  }

