<?php
/**
 *  Copyright 2014 Taxamo, Ltd.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Settlement_report_entry {

  static $swaggerTypes = array(
      'tax_currency_code' => 'string',
      'name' => 'string',
      'tax_amount' => 'number',
      'fx_rate' => 'number',
      'total_amount' => 'number',
      'tax_rate' => 'number',
      'amount' => 'number',
      'tax_amount_in_currency' => 'number',
      'currency_code' => 'string'

    );

  /**
  * 3-letter ISO currency code for tax.
  */
  public $tax_currency_code; // string
  /**
  * Tax country name
  */
  public $name; // string
  /**
  * Tax amoount, in base currency.
  */
  public $tax_amount; // number
  /**
  * Foreign exchange rate used to convert to target currency.
  */
  public $fx_rate; // number
  /**
  * Total amount, including tax, in base currency.
  */
  public $total_amount; // number
  /**
  * Tax rate applied.
  */
  public $tax_rate; // number
  /**
  * Amount, without tax, in base currency.
  */
  public $amount; // number
  /**
  * Tax amount in currency.
  */
  public $tax_amount_in_currency; // number
  /**
  * Original currency code.
  */
  public $currency_code; // string
  }

